name: Test workflow

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      applications:
        description: 'Select application to test'
        required: true
        default: 'app1'
        type: choice
        options:
        - app1
        - app2
        - both

jobs:
  create-important-job:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issue_comment' &&
      (contains(github.event.comment.body, '/test') || contains(github.event.comment.body, '/hello')) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Create artifact
        if: |
          contains(github.event.comment.body, '/test') ||
          github.event.inputs.applications == 'app1' ||
          github.event.inputs.applications == 'both'
        run: echo 'I only run for test'
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: important-document
          path: README.md

  print-important-job:
    runs-on: ubuntu-latest
    needs: create-important-job
    if: |
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '/test') ||
      github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.applications == 'app1' || github.event.inputs.applications == 'both')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: important-document
      - name: Print README.md
        run: cat README.md
  print-hello-job:
    runs-on: ubuntu-latest
    needs: create-important-job
    if: |
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '/hello') ||
      github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.applications == 'app2' || github.event.inputs.applications == 'both')
    steps:
      - name: Hello
        run: echo "Hello"