name: PR tests

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
    wait-print-readme-success:
        name: jest-tsc-lint
        runs-on: ubuntu-latest
        steps:
          - name: Wait for tests to succeed
            uses: lewagon/wait-on-check-action@v1.3.1
            with:
              ref: ${{ github.ref }}
              check-name: 'Test workflow'
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              wait-interval: 10
